import os
from datetime import datetime
import numpy as np
import pandas as pd
import requests
import yfinance as yf

# Ambil token secara aman dari GitHub Secrets
TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
CHAT_ID = os.getenv('CHAT_ID')

# Range Harga Bisa Diubah Otomatis di Sini
MIN_PRICE = 70
MAX_PRICE = 1000

raw_tickers = [
    'AADI',
    'AALI',
    'ABMM',
    'ACES',
    'ACST',
    'ADCP',
    'ADES',
    'ADHI',
    'ADMG',
    'ADMR',
    'ADRO',
    'AGAR',
    'AGII',
    'AIMS',
    'AISA',
    'AKKU',
    'AKPI',
    'AKRA',
    'AKSI',
    'ALDO',
    'ALKA',
    'AMAN',
    'AMFG',
    'AMIN',
    'ANDI',
    'ANJT',
    'ANTM',
    'APII',
    'APLI',
    'APLN',
    'ARCI',
    'AREA',
    'ARGO',
    'ARII',
    'ARNA',
    'ARTA',
    'ASGR',
    'ASHA',
    'ASII',
    'ASLC',
    'ASLI',
    'ASPI',
    'ASRI',
    'ASSA',
    'ATAP',
    'ATIC',
    'ATLA',
    'AUTO',
    'AVIA',
    'AWAN',
    'AXIO',
    'AYAM',
    'AYLS',
    'BABY',
    'BAIK',
    'BANK',
    'BAPI',
    'BATA',
    'BATR',
    'BAUT',
    'BAYU',
    'BBRM',
    'BBSS',
    'BCIP',
    'BDKR',
    'BEEF',
    'BELI',
    'BELL',
    'BESS',
    'BEST',
    'BIKE',
    'BINO',
    'BIPP',
    'BIRD',
    'BISI',
    'BKDP',
    'BKSL',
    'BLES',
    'BLOG',
    'BLTA',
    'BLTZ',
    'BLUE',
    'BMHS',
    'BMSR',
    'BMTR',
    'BNBR',
    'BOAT',
    'BOBA',
    'BOGA',
    'BOLA',
    'BOLT',
    'BRAM',
    'BRIS',
    'BRMS',
    'BRNA',
    'BRPT',
    'BRRC',
    'BSBK',
    'BSDE',
    'BSML',
    'BSSR',
    'BTPS',
    'BUAH',
    'BUKK',
    'BULL',
    'BUMI',
    'BUVA',
    'BYAN',
    'CAKK',
    'CAMP',
    'CANI',
    'CARE',
    'CASS',
    'CBDK',
    'CBPE',
    'CBRE',
    'CCSI',
    'CEKA',
    'CGAS',
    'CHEK',
    'CHEM',
    'CINT',
    'CITA',
    'CITY',
    'CLEO',
    'CLPI',
    'CMNP',
    'CMPP',
    'CMRY',
    'CNKO',
    'CNMA',
    'COAL',
    'CPIN',
    'CPRO',
    'CRAB',
    'CRSN',
    'CSAP',
    'CSIS',
    'CSMI',
    'CSRA',
    'CTBN',
    'CTRA',
    'CYBR',
    'DAAZ',
    'DADA',
    'DATA',
    'DAYA',
    'DCII',
    'DEFI',
    'DEPO',
    'DEWA',
    'DEWI',
    'DGIK',
    'DGNS',
    'DGWG',
    'DILD',
    'DIVA',
    'DKFT',
    'DKHH',
    'DMAS',
    'DMMX',
    'DMND',
    'DOOH',
    'DOSS',
    'DRMA',
    'DSFI',
    'DSNG',
    'DSSA',
    'DUTI',
    'DVLA',
    'DWGL',
    'DYAN',
    'EAST',
    'ECII',
    'EDGE',
    'EKAD',
    'ELIT',
    'ELPI',
    'ELSA',
    'ELTY',
    'EMDE',
    'ENAK',
    'ENRG',
    'EPAC',
    'EPMT',
    'ERAA',
    'ERAL',
    'ESIP',
    'ESSA',
    'ESTA',
    'EXCL',
    'FAST',
    'FASW',
    'FILM',
    'FIRE',
    'FISH',
    'FITT',
    'FMII',
    'FOLK',
    'FOOD',
    'FORE',
    'FPNI',
    'FUTR',
    'FWCT',
    'GDST',
    'GDYR',
    'GEMA',
    'GEMS',
    'GGRP',
    'GHON',
    'GIAA',
    'GJTL',
    'GLVA',
    'GMTD',
    'GOLD',
    'GOLF',
    'GOOD',
    'GPRA',
    'GPSO',
    'GRIA',
    'GRPH',
    'GTBO',
    'GTRA',
    'GTSI',
    'GULA',
    'GUNA',
    'GWSA',
    'GZCO',
    'HADE',
    'HAIS',
    'HALO',
    'HATM',
    'HDIT',
    'HEAL',
    'HERO',
    'HEXA',
    'HGII',
    'HITS',
    'HOKI',
    'HOMI',
    'HOPE',
    'HRME',
    'HRUM',
    'HUMI',
    'HYGN',
    'IATA',
    'IBST',
    'ICBP',
    'ICON',
    'IDPR',
    'IFII',
    'IFSH',
    'IGAR',
    'IIKP',
    'IKAI',
    'IKAN',
    'IKBI',
    'IKPM',
    'IMPC',
    'INCI',
    'INCO',
    'INDF',
    'INDR',
    'INDS',
    'INDX',
    'INDY',
    'INET',
    'INKP',
    'INPP',
    'INTD',
    'INTP',
    'IOTF',
    'IPCC',
    'IPCM',
    'IPOL',
    'IPTV',
    'IRRA',
    'IRSX',
    'ISAT',
    'ISSP',
    'ITMA',
    'ITMG',
    'JAST',
    'JATI',
    'JAWA',
    'JAYA',
    'JECC',
    'JGLE',
    'JIHD',
    'JKON',
    'JMAS',
    'JPFA',
    'JRPT',
    'JSMR',
    'JSPT',
    'JTPE',
    'KAQI',
    'KARW',
    'KBAG',
    'KBLI',
    'KBLM',
    'KDSI',
    'KDTN',
    'KEEN',
    'KEJU',
    'KETR',
    'KIAS',
    'KICI',
    'KIJA',
    'KINO',
    'KIOS',
    'KJEN',
    'KKES',
    'KKGI',
    'KLAS',
    'KLBF',
    'KMDS',
    'KOBX',
    'KOCI',
    'KOIN',
    'KOKA',
    'KONI',
    'KOPI',
    'KOTA',
    'KPIG',
    'KREN',
    'KRYA',
    'KSIX',
    'KUAS',
    'LABA',
    'LABS',
    'LAJU',
    'LAND',
    'LCKM',
    'LION',
    'LIVE',
    'LMPI',
    'LMSH',
    'LPCK',
    'LPIN',
    'LPKR',
    'LPLI',
    'LPPF',
    'LRNA',
    'LSIP',
    'LTLS',
    'LUCK',
    'MAHA',
    'MAIN',
    'MAPA',
    'MAPB',
    'MAPI',
    'MARK',
    'MAXI',
    'MBAP',
    'MBMA',
    'MBTO',
    'MCAS',
    'MCOL',
    'MDIY',
    'MDKA',
    'MDKI',
    'MDLA',
    'MEDC',
    'MEDS',
    'MERI',
    'MERK',
    'META',
    'MFMI',
    'MGNA',
    'MHKI',
    'MICE',
    'MIDI',
    'MIKA',
    'MINA',
    'MINE',
    'MIRA',
    'MITI',
    'MKAP',
    'MKPI',
    'MKTR',
    'MLIA',
    'MLPL',
    'MLPT',
    'MMIX',
    'MMLP',
    'MNCN',
    'MORA',
    'MPIX',
    'MPMX',
    'MPOW',
    'MPPA',
    'MPRO',
    'MRAT',
    'MSIN',
    'MSJA',
    'MSKY',
    'MSTI',
    'MTDL',
    'MTEL',
    'MTFN',
    'MTLA',
    'MTMH',
    'MTPS',
    'MTSM',
    'MUTU',
    'MYOH',
    'MYOR',
    'NAIK',
    'NASA',
    'NASI',
    'NCKL',
    'NELY',
    'NEST',
    'NETV',
    'NFCX',
    'NICE',
    'NICL',
    'NIKL',
    'NPGF',
    'NRCA',
    'NTBK',
    'NZIA',
    'OASA',
    'OBAT',
    'OBMD',
    'OILS',
    'OKAS',
    'OMED',
    'OMRE',
    'PADA',
    'PALM',
    'PAMG',
    'PANI',
    'PANR',
    'PART',
    'PBID',
    'PBSA',
    'PCAR',
    'PDES',
    'PDPP',
    'PEHA',
    'PEVE',
    'PGAS',
    'PGEO',
    'PGLI',
    'PGUN',
    'PICO',
    'PIPA',
    'PJAA',
    'PJHB',
    'PKPK',
    'PLIN',
    'PMJS',
    'PMUI',
    'PNBS',
    'PNGO',
    'PNSE',
    'POLI',
    'POLU',
    'PORT',
    'POWR',
    'PPRE',
    'PPRI',
    'PPRO',
    'PRAY',
    'PRDA',
    'PRIM',
    'PSAB',
    'PSAT',
    'PSDN',
    'PSGO',
    'PSKT',
    'PSSI',
    'PTBA',
    'PTIS',
    'PTMP',
    'PTMR',
    'PTPP',
    'PTPS',
    'PTPW',
    'PTSN',
    'PTSP',
    'PURA',
    'PURI',
    'PWON',
    'PZZA',
    'RAAM',
    'RAFI',
    'RAJA',
    'RALS',
    'RANC',
    'RATU',
    'RBMS',
    'RDTX',
    'RGAS',
    'RIGS',
    'RISE',
    'RMKE',
    'RMKO',
    'ROCK',
    'RODA',
    'RONY',
    'ROTI',
    'RSGK',
    'RUIS',
    'SAFE',
    'SAGE',
    'SAME',
    'SAMF',
    'SAPX',
    'SATU',
    'SBMA',
    'SCCO',
    'SCNP',
    'SCPI',
    'SEMA',
    'SGER',
    'SGRO',
    'SHID',
    'SHIP',
    'SICO',
    'SIDO',
    'SILO',
    'SIMP',
    'SIPD',
    'SKBM',
    'SKLT',
    'SKRN',
    'SLIS',
    'SMAR',
    'SMBR',
    'SMCB',
    'SMDM',
    'SMDR',
    'SMGA',
    'SMGR',
    'SMIL',
    'SMKL',
    'SMLE',
    'SMMT',
    'SMRA',
    'SMSM',
    'SNLK',
    'SOCI',
    'SOHO',
    'SOLA',
    'SONA',
    'SOSS',
    'SOTS',
    'SPMA',
    'SPTO',
    'SRTG',
    'SSIA',
    'SSTM',
    'STAA',
    'STTP',
    'SULI',
    'SUNI',
    'SUPR',
    'SURI',
    'SWID',
    'TALF',
    'TAMA',
    'TAMU',
    'TAPG',
    'TARA',
    'TAXI',
    'TBMS',
    'TCID',
    'TCPI',
    'TEBE',
    'TFAS',
    'TFCO',
    'TGKA',
    'TGUK',
    'TINS',
    'TIRA',
    'TIRT',
    'TKIM',
    'TLDN',
    'TLKM',
    'TMAS',
    'TMPO',
    'TNCA',
    'TOBA',
    'TOOL',
    'TOSK',
    'TOTL',
    'TOTO',
    'TPIA',
    'TPMA',
    'TRIS',
    'TRJA',
    'TRON',
    'TRST',
    'TRUE',
    'TRUK',
    'TSPC',
    'TYRE',
    'UANG',
    'UCID',
    'UFOE',
    'ULTJ',
    'UNIC',
    'UNIQ',
    'UNTR',
    'UNVR',
    'UVCR',
    'VAST',
    'VERN',
    'VICI',
    'VISI',
    'VKTR',
    'VOKS',
    'WAPO',
    'WBSA',
    'WEGE',
    'WEHA',
    'WINR',
    'WINS',
    'WIRG',
    'WMUU',
    'WOOD',
    'WOWS',
    'WTON',
    'YELO',
    'YPAS',
    'YUPI',
    'ZATA',
    'ZONE',
    'ZYRX',
]

saham_watchList = list(set([f'{t}.JK' for t in raw_tickers]))
print(f'Total Watchlist Dimuat: {len(saham_watchList)} emiten.')


def send_telegram_message(message):
  url = f'https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage'
  payload = {'chat_id': CHAT_ID, 'text': message, 'parse_mode': 'Markdown'}
  try:
    requests.post(url, json=payload)
  except Exception as e:
    print(f'Gagal kirim Telegram: {e}')


def calculate_smiio(df, e1=5, e2=20, signal_len=5):
  hh = df['High'].rolling(e2).max()
  ll = df['Low'].rolling(e2).min()
  m = df['Close'] - 0.5 * (hh + ll)
  r = hh - ll
  smooth_m = (
      m.ewm(span=e1, adjust=False).mean().ewm(span=e2, adjust=False).mean()
  )
  smooth_r = (
      r.ewm(span=e1, adjust=False).mean().ewm(span=e2, adjust=False).mean()
  )
  smi = np.where(smooth_r != 0, 100 * (smooth_m / (0.5 * smooth_r)), 0)
  smi_series = pd.Series(smi, index=df.index)
  smi_signal = smi_series.ewm(span=signal_len, adjust=False).mean()
  return smi_series, smi_signal


def calculate_stoch(df, period=20, smooth_k=3, smooth_d=3):
  low_min = df['Low'].rolling(window=period).min()
  high_max = df['High'].rolling(window=period).max()
  k_fast = 100 * (df['Close'] - low_min) / (high_max - low_min)
  stoch_k = k_fast.rolling(window=smooth_k).mean()
  stoch_d = stoch_k.rolling(window=smooth_d).mean()
  return stoch_k, stoch_d


print(
    f'🔍 MenScanning Sinyal Batch ({datetime.now().strftime("%Y-%m-%d %H:%M")})...'
)
signals_today = []

try:
  data_chunk = yf.download(
      saham_watchList,
      period='6mo',
      interval='1d',
      group_by='ticker',
      progress=True,
  )

  for ticker in saham_watchList:
    try:
      if ticker not in data_chunk.columns.levels[0]:
        continue
      df = data_chunk[ticker].copy()

      if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

      df = df[['Open', 'High', 'Low', 'Close', 'Volume']].dropna()
      if len(df) < 60:
        continue

      df['Val_MA20'] = (df['Close'] * df['Volume']).rolling(20).mean()
      df['MA20'] = df['Close'].rolling(20).mean()
      df['MA50'] = df['Close'].rolling(50).mean()
      df['Vol_MA20'] = df['Volume'].rolling(20).mean()
      df['SMIIO'], df['SMIIO_Sig'] = calculate_smiio(df)
      df['Stoch_K'], df['Stoch_D'] = calculate_stoch(df)

      i = len(df) - 1
      c_today = df['Close'].iloc[i]
      c_yest = df['Close'].iloc[i - 1]
      o_today = df['Open'].iloc[i]
      vol_today = df['Volume'].iloc[i]
      val_ma20 = df['Val_MA20'].iloc[i]

      if not (MIN_PRICE <= c_today <= MAX_PRICE) or val_ma20 < 1_000_000_000:
        continue

      smi_gc = (df['SMIIO'].iloc[i - 1] <= df['SMIIO_Sig'].iloc[i - 1]) and (
          df['SMIIO'].iloc[i] > df['SMIIO_Sig'].iloc[i]
      )
      smi_slope_up = df['SMIIO'].iloc[i] > df['SMIIO'].iloc[i - 1]

      if not (smi_gc and smi_slope_up):
        continue

      stoch_gc = (df['Stoch_K'].iloc[i - 1] <= df['Stoch_D'].iloc[i - 1]) and (
          df['Stoch_K'].iloc[i] > df['Stoch_D'].iloc[i]
      )
      above_ma20 = c_today >= df['MA20'].iloc[i]
      vol_spike = vol_today >= (1.2 * df['Vol_MA20'].iloc[i])
      green_candle = c_today >= o_today and c_today >= c_yest
      is_uptrend = df['MA20'].iloc[i] > df['MA50'].iloc[i]

      score = 0
      if smi_gc:
        score += 25
      if stoch_gc:
        score += 25
      if above_ma20:
        score += 20
      if vol_spike:
        score += 15
      if green_candle:
        score += 15

      chg_pct = ((c_today - c_yest) / c_yest) * 100
      is_not_ara = (chg_pct < 32.0) if c_today < 200 else (chg_pct < 23.0)

      if score >= 70 and is_not_ara and is_uptrend:
        signals_today.append(
            {
                'Ticker': ticker.replace('.JK', ''),
                'Close': int(c_today),
                'Score': score,
            }
        )
    except:
      continue
except Exception as e:
  print(f'Gagal unduh data: {e}')

if signals_today:
  msg = "🚨 *SWING SMIIO BATCH SIGNAL* 🚨\n"
  msg += (
      f"📅 Tanggal: {datetime.now().strftime('%Y-%m-%d %H:%M')} WIB\n"
      f"🔍 Range Harga: {MIN_PRICE} - {MAX_PRICE}\n\n"
      "Kandidat Saham Hari Ini:\n"
  )
  for s in signals_today:
    msg += f"• *${s['Ticker']}* | Harga: {s['Close']} | Skor: {s['Score']}\n"
  msg += "\n_Cek manual chart sebelum eksekusi!_"

  send_telegram_message(msg)
  print('\n🎯 Sinyal ditemukan dan berhasil dikirim ke Telegram!')
  print(pd.DataFrame(signals_today).to_string(index=False))
else:
  print(
      f'\n📭 NIHIL! Tidak ada saham di range harga {MIN_PRICE}-{MAX_PRICE} yang'
      ' lolos filter.'
  )
